# Generated by Django 4.0.5 on 2022-07-04 07:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_created_at_profile_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="profile_pics"
            ),
        ),
    ]
