# Generated by Django 4.0.5 on 2022-06-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userfollowing_userfollowing_unique_following"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfollowing",
            name="unique_following",
        ),
        migrations.RenameField(
            model_name="userfollowing",
            old_name="following_user_id",
            new_name="followed",
        ),
        migrations.RenameField(
            model_name="userfollowing",
            old_name="user_id",
            new_name="follower",
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                fields=("follower", "followed"), name="unique_following"
            ),
        ),
    ]
