# Generated by Django 4.0.5 on 2022-07-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_image"),
        ("users", "0005_alter_userfollowing_follower"),
    ]

    operations = []
