# Generated by Django 4.0.5 on 2022-07-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userfollowing_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lookup_id',
            field=models.CharField(default='dsadsakllsda', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
