# Generated by Django 4.0.5 on 2022-07-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_merge_20220704_2316"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollowing",
        ),
    ]
