# Generated by Django 4.0.5 on 2022-07-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_verified_user_lookup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lookup_id',
            field=models.CharField(default='b60de1a17aa84639a68eb634529b1199', editable=False, max_length=255, unique=True),
        ),
    ]
