# Generated by Django 4.0.5 on 2022-07-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userfollowing_follower"),
        ("users", "0008_alter_profile_bio_alter_profile_image"),
    ]

    operations = []
