# Generated by Django 4.0.5 on 2022-07-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_delete_userfollowing"),
        ("users", "0009_alter_profile_bio_alter_profile_image"),
    ]

    operations = []
