# Generated by Django 4.0.5 on 2022-07-29 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_userfollowing_userfollowing_unique_following"),
        ("articles", "0002_alter_article_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=500)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "highlight_start",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "highlight_end",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("highlight_text", models.TextField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article",
                        to="articles.article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-createdAt"],
            },
        ),
    ]
