# Generated by Django 4.0.5 on 2022-07-29 08:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="lookup_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
