# Generated by Django 4.0.5 on 2022-08-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_comment_lookup_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="updatedAt",
            new_name="updated_at",
        ),
    ]
